name: "Build & Release"

# This worflow needs those secrets:
#
# DOCKERPASSWORD = Docker Hub token

on:
  push:
    branches:
      - 'master'
      - 'main'
  workflow_dispatch:
  repository_dispatch:
    types:
      - 'new-version'
  pull_request:
    types: [assigned, opened, synchronize, reopened]

env:
  PLATFORMS: "linux/amd64,linux/arm/v7,linux/arm64"     # Build for which platforms
  UPSTREAM_GITHUB_REPOSITORY: othalla/plex_exporter

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          repository: ${{ env.UPSTREAM_GITHUB_REPOSITORY }}
      -
        name: Get current version
        id: get_version
        run: |
          version=$(curl --silent https://api.github.com/repos/${GITHUB_REPOSITORY}/git/refs/tags | jq -r '.[-1].ref' | awk -F/ '{print $NF}')
          if [[ $version =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            version="v${version}"
          fi
          echo "::debug::get current version ${version}"
          echo "::set-output name=version::${version}"
      -
        name: Generate Build-Args
        id: build-args
        run: |
          # echo ::set-output name=build-arg1::"buildarg1"
          # echo ::set-output name=build-arg2::"buildarg2"
      - 
        name: Prepare
        id: prep
        run: |
          IMAGENAME=$(echo ${{ github.repository }} | sed 's/${{ github.repository_owner }}\/docker-//g')
          IMAGEPREFIX="ghcr.io/${{ github.repository_owner }}"
          IMAGE="${IMAGEPREFIX}/${IMAGENAME}"

          if [[ $github.event_name = repository_dispatch ]]; then
            VERSION=${{ steps.get_version.outputs.version }}
            TAGS="${IMAGE}:${VERSION}"
            if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
              MINOR=${VERSION%.*}
              MAJOR=${MINOR%.*}
              TAGS="$TAGS,${IMAGE}:${MINOR},${IMAGE}:${MAJOR},${IMAGE}:latest"
            fi
          else
            VERSION=nightly
            TAGS="${IMAGE}:${VERSION}"
          fi
          ###### FIX DOCKERFILE #######
          sed -i "s/GOARCH=amd64//g" Dockerfile
          #############################
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=imagename::${IMAGENAME}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      # -
      #   name: Hadolint
      #   uses: brpaz/hadolint-action@v1.5.0
      #   with: 
      #     dockerfile: Dockerfile
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
      -
        name: Login to GHCR
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
          build-args: |
            ${{ steps.build-args.outputs.build-arg1 }}
            ${{ steps.build-args.outputs.build-arg2 }}
          labels: |
            org.opencontainers.image.title=${{ steps.prep.outputs.imagename }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.version=${{ steps.prep.outputs.version }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
